site_name: ZEC的Blog/Doc
site_url: http://zec_cn.pages.dev
site_description: ZEC的Blog/Doc网站 By makedocs
site_author: ZEC

repo_url: https://github.com/ZEC-dev/ZEC-dev.github.io/

copyright: Copyright &copy; 2013 <a href="https://zec_cn.pages.dev">ZEC</a>.

theme:
    name: cosmo

nav :
    - 首页: index.md 
    - 入门指南: getting-started.md

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
